In [2]:
import numpy as np


In [6]:
ls = [1,2,3]
arr = np.array(ls)
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [10]:
arr.size

3

In [12]:
arr.shape

(3,)

In [17]:
np.array([1,2,3.4,10.9, 2+5j])

array([ 1. +0.j,  2. +0.j,  3.4+0.j, 10.9+0.j,  2. +5.j])

In [21]:
np.array([1,2,3.4,10.9], dtype='int')

array([ 1,  2,  3, 10])

In [41]:
new_arr = np.array([[12,43,33],
         [1,2,3],
         [23,34,23]])

In [32]:
np.array([[12,43,33],
         [1,2,3],
         [23,34,None]])

array([[12, 43, 33],
       [1, 2, 3],
       [23, 34, None]], dtype=object)

In [39]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [46]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [56]:
arr = np.array([[[1,2,3],
                [4,5,6],
                 [7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [58]:
arr.flatten() # n-dimensional array is converted into 1-dimensional array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [64]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [69]:
np.ones([2,3,4])


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [71]:
np.full(10,4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [73]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [76]:
np.full([2,3],[7,8,9])

array([[7, 8, 9],
       [7, 8, 9]])

In [79]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.random.randint(1,101,5)

array([ 8, 31, 76, 26, 25], dtype=int32)

In [94]:
np.random.randint(100,200,[3,4])

array([[111, 126, 179, 137],
       [170, 121, 103, 190],
       [178, 132, 156, 181]], dtype=int32)

In [97]:
np.random.rand(1,10,5)

array([[[0.16176457, 0.8007678 , 0.43870935, 0.46243932, 0.32536367],
        [0.82654279, 0.88981368, 0.59689387, 0.06092237, 0.26056505],
        [0.02703677, 0.20243048, 0.40821861, 0.44116718, 0.21528456],
        [0.87746999, 0.79002149, 0.99255729, 0.57029266, 0.15060494],
        [0.3019958 , 0.56462263, 0.2359881 , 0.4862414 , 0.4522947 ],
        [0.6313249 , 0.4296837 , 0.5993413 , 0.28511662, 0.68648595],
        [0.02088073, 0.35241638, 0.38956346, 0.79637487, 0.90857325],
        [0.14101643, 0.40928314, 0.92875652, 0.76676626, 0.17592682],
        [0.15915305, 0.00857213, 0.5766554 , 0.51751824, 0.13986116],
        [0.51930199, 0.41821608, 0.18731754, 0.64001551, 0.64645196]]])

In [100]:
np.linspace(2,5, retstep = True)

(array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
        2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
        2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
        2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
        3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
        3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
        3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
        4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
        4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
        4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]),
 np.float64(0.061224489795918366))

In [103]:
arr = np.arange(1,11).reshape([2,5])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### ***COPY and VIEW***

In [ ]:
new_arr = arr.view()  # copy reference address
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [106]:
arr[0][0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [109]:
new_arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [ ]:
new_arr_copy = arr.copy() # copy values
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [ ]:
arr[0][0] = 1000
arr

array([[1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10]])

In [115]:
new_arr_copy

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])